### ISSUE TITLE
Categorize item related class into its own package

### ISSUE THREAD

**Issue by zulq9** [CS2103-AY1819S1-W14-4/main#114]
Here is an example from logic component:

<img width="173" alt="1d" src="https://user-images.githubusercontent.com/39236810/47612800-f857a380-dabc-11e8-98e2-ddff85139ee2.PNG">

By categorizing, it would be easier for us to navigate and access the files. 😄

**Comment by yao-tx** [comment]
okay, I will sort these out when all the PRs are more or less settled.
