### ISSUE TITLE
Can give brief instruction which command users can do after login

### ISSUE THREAD

**Issue by fzdy1914** [CS2103-AY1819S1-W14-4/main#137]

**Comment by fzdy1914** [comment]
@darren96 I found a little lost after login, may can give some instructions after login.

**Comment by darren96** [comment]
Ok, will update the UG after Wednesday.

**Comment by fzdy1914** [comment]
@darren96 
![image](https://user-images.githubusercontent.com/35621726/47724763-440f7600-dc92-11e8-9770-67329878ac1d.png)
I mean you can give some instruction here

**Comment by fzdy1914** [comment]
If you think its not necessary, its ok

**Comment by darren96** [comment]
Ah, as in, I don't think it is needed here. They can always refer back to UG. 😄

**Comment by fzdy1914** [comment]
I saw Zul have updated some of the instruction recently

**Comment by darren96** [comment]
Ok, I guess I can have this issue closed right?
